name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pytest black isort

      - name: Lint (isort, black)
        run: |
          isort --check-only .
          black --check .

      - name: Run docspec tests only
        run: |
          pytest -q

      - name: Run full test suite
        run: |
          pytest -q -m 'not docspec'


